name: "Deploy server"

on:
  push:
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  CI:
    name: "Continuous Integration"
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push http image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          target: http
          push: true
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.APP_NAME }}-http:${{ github.sha }}"
      - name: Build and push queue image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          target: queue
          push: true
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.APP_NAME }}-queue:${{ github.sha }}"
      - name: Build and push scheduler image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          target: scheduler
          push: true
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.APP_NAME }}-scheduler:${{ github.sha }}"
      - name: Copy Proxy stack to server
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: spring-boot-games-nice.henrotaym.ip-ddns.com
          remote-user: ${{ secrets.SSH_USER }}
          private-ssh-key: ${{ secrets.SSH_KEY }}
          source-path: ./devops/deployment/proxy/
          destination-path: ~/apps/proxy/
      - name: Copy App stack to server
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: spring-boot-games-nice.henrotaym.ip-ddns.com
          remote-user: ${{ secrets.SSH_USER }}
          private-ssh-key: ${{ secrets.SSH_KEY }}
          source-path: ./devops/deployment/app/
          destination-path: ~/apps/${{ secrets.APP_NAME }}/
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Deploy Proxy stack
        run: |
          ssh-keyscan -t rsa ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "docker stack deploy -c /home/ubuntu/apps/proxy/docker-compose.yml --detach=false proxy"
      - name: Deploy App stack
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "export IMAGE_TAG=${{ github.sha }} doppler run --token=${{ secrets.DOPPLER_TOKEN }} -- docker stack deploy -c /home/ubuntu/apps/spring-boot-games/docker-compose.yml --detach=false spring-boot-games"
      